### ISSUE TITLE
trouble building compiler_builtins

### ISSUE THREAD

**Issue by erik-nymi** [ctron/rust-esp-container#4]
Running on MacOS host...

I keep running into this problem when running `build-project`:

`docker run -ti -v $PWD:/build quay.io/ctron/rust-esp:latest`

```
...
warning: Patch `rustc-std-workspace-core v1.0.0 (/rust-xtensa/src/tools/rustc-std-workspace-core)` was not used in the crate graph.
Check that the patched package version and available features are compatible
with the dependency requirements. If the patch has a different version from
what is locked in the Cargo.lock file, run `cargo update` to use the new
version. This may also occur with an optional dependency that is not enabled.
  Downloaded compiler_builtins v0.1.16
  Downloaded 1 crates (131.3 KB) in 0.40s
   Compiling compiler_builtins v0.1.16
error[E0463]: can't find crate for `core`
  |
  = note: the `xtensa-esp32-none-elf` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `compiler_builtins`.
```
I'm not sure if it's my environment or if I missed a step. My project is a clone of your template.

**Comment by ctron** [comment]
I added a note to the README about `compiler_builtins`: https://github.com/ctron/rust-esp-container

---
**Note:** I recently noticed an issue compiling the `compiler_builtins`. It looks like some newly introduced issue.
The workaround is to switch back to an older version of `compiler_builtins` in `Xargo.toml`:

~~~toml
[dependencies]
compiler_builtins = { version = "=0.1.16" }
~~~
---

**Comment by erik-nymi** [comment]
I was able to resolve this myself. I think I missed a step.
